src/GamingStore/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GamingStore.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GamingStore.Data;
using GamingStore.Models;
using GamingStore.ViewModels;
using GamingStore.ViewModels.Cart;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GamingStore.Controllers
{
    [Route("cart")]
    public class CartsController : BaseController
    {
        public CartsController(UserManager<User> userManager, GamingStoreContext context, RoleManager<IdentityRole> roleManager, SignInManager<User> signInManager)
            : base(userManager, context, roleManager, signInManager)
        {
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            try
            {
                User User = await GetCurrentUserAsync();
                IQueryable<Cart> itemsInCart = Context.Cart.Where(c => c.UserId == User.Id);

                foreach (Cart cartItem in itemsInCart)
                {
                    Item item = Context.Item.First(i => i.Id == cartItem.ItemId);
                    cartItem.Item = item;
                }

                var itemsPrice = 0.00;

                foreach (Cart cart in itemsInCart)
                {
                    itemsPrice += cart.Item.Price * cart.Quantity;
                }

                var viewModel = new CartViewModel
                {
                    Carts = await itemsInCart.ToListAsync(),
                    Payment = new Payment
                    {
                        ItemsCost = itemsPrice
                    },
                    ItemsInCart = await CountItemsInCart()
                };

                return View(viewModel);
            }
            catch
            {
                //no items in cart
                return View(new CartViewModel { ItemsInCart = 0 });
            }
        }

        
        [Authorize]
        [HttpPost("DeleteItemInCart")]
        public async Task<IActionResult> DeleteItemInCart(int id)
        {
            IQueryable<Cart> cart = Context.Cart.Where(c => c.Id == id);
            Context.Cart.RemoveRange(cart);
            await Context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost("Delete")]
        [Authorize]
        public async Task<IActionResult> Delete()
        {
            User User = await GetCurrentUserAsync();
            IQueryable<Cart> cart = Context.Cart.Where(c => c.UserId == User.Id);
            Context.Cart.RemoveRange(cart);
            await Context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

src/GamingStore/Controllers/ItemsController.cs
using GamingStore.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GamingStore.Data;
using GamingStore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GamingStore.ViewModels.Items;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using GamingStore.Services.Twitter;
using Microsoft.AspNetCore.Mvc.Rendering;
using GamingStore.Contracts;
using Microsoft.AspNetCore.Http;

namespace GamingStore.Controllers
{
    public class ItemsController : BaseController
    {
        private readonly GamingStoreContext _context;


        public ItemsController(UserManager<User> userManager, GamingStoreContext context, RoleManager<IdentityRole> roleManager, SignInManager<User> signInManager)
            : base(userManager, context, roleManager, signInManager)
        {
            _context = context;
        }


        // Search
        public async Task<IActionResult> Search(string[] brands, string[] category, double price, string queryTitle, int? pageNumber)
        {
            var searchItems = _context.Item.Where(a => (brands.Contains(a.Brand) || brands.Length == 0) && (category.Contains(a.Category.Name) || category.Length == 0) && (a.Price <= price || price == 0) && (a.Title.Contains(queryTitle) || queryTitle == null) && (a.Active));

            const int pageSize = 200;

            List<string> theBrands = brands.ToList();

            List<string> theCategories = category.ToList();

            PaginatedList<Item> paginatedList = await PaginatedList<Item>.CreateAsync(searchItems.AsNoTracking(), pageNumber ?? 1, pageSize);

            double thePrice = price;

            string theQueryTitle = queryTitle;

            //for all the items

            IQueryable<Item> allItems = _context.Item.Where(i => i.Active);

            List<string> allBrands = allItems.Select(i => i.Brand).Distinct().ToList();

            List<string> allCategories = allItems.Select(i => i.Category.Name).Distinct().ToList();


            var viewModel = new GetChosenItemsViewModel()
            {
                Categories = theCategories,
                Brands = theBrands,
                Items = searchItems.ToArray(),
                PaginatedItems = paginatedList,
                Price = thePrice,
                QueryTitle = theQueryTitle,

                AllItems = allItems.ToArray(),
                AllBrands = allBrands,
                AllCategories = allCategories,

                ItemsInCart = await CountItemsInCart()
            };

            return View("~/Views/Items/chosenIndex.cshtml", viewModel);
        }


        public async Task<IActionResult> CategoryItems(int? id, int? pageNumber)
        {
            var searchItems = _context.Item.Where(i => i.CategoryId == id && i.Active);

            const int pageSize = 200;

            List<string> theBrands = new List<string>();

            List<string> theCategories = new List<string>();

            foreach (var category in _context.Category)
            {
                if (category.Id == id)
                {
                    theCategories.Add(category.Name);
                    break;
                }
            }

            PaginatedList<Item> paginatedList = await PaginatedList<Item>.CreateAsync(searchItems.AsNoTracking(), pageNumber ?? 1, pageSize);

            //for all the items

            IQueryable<Item> allItems = _context.Item.Where(i => i.Active);

            List<string> allBrands = allItems.Select(i => i.Brand).Distinct().ToList();

            List<string> allCategories = allItems.Select(i => i.Category.Name).Distinct().ToList();

            var viewModel = new GetChosenItemsViewModel()
            {
                Categories = theCategories,
                Brands = theBrands,
                Items = searchItems.ToArray(),
                PaginatedItems = paginatedList,
                Price = 0.0,
                QueryTitle = null,

                AllItems = allItems.ToArray(),
                AllBrands = allBrands,
                AllCategories = allCategories,

                ItemsInCart = await CountItemsInCart()
            };

            if (id == null)
            {
                return NotFound();
            }

            return View("~/Views/Items/chosenIndex.cshtml", viewModel);
        }

        // GET: Items
        public async Task<IActionResult> Index(int? pageNumber)
        {
            const int pageSize = 200;

            IQueryable<Item> items = _context.Item.Where(i => i.Active);

            List<string> brands = items.Select(i => i.Brand).Distinct().ToList();

            List<string> categories = items.Select(i => i.Category.Name).Distinct().ToList();

            PaginatedList<Item> paginatedList = await PaginatedList<Item>.CreateAsync(items.AsNoTracking(), pageNumber ?? 1, pageSize);

            var viewModel = new GetItemsViewModel()
            {
                Categories = categories,
                Brands = brands,
                Items = items.ToArray(),
                PaginatedItems = paginatedList,


                ItemsInCart = await CountItemsInCart()
            };



            return View(viewModel);
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(i => i.Category)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            var viewModel = new ItemViewModel()
            {
                Item = item,
                ItemsInCart = await CountItemsInCart()
            };

            return View(viewModel);
        }

        // GET: Items/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["Categories"] = new SelectList(_context.Category, nameof(Category.Id), nameof(Category.Name));
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateItemViewModel model)
        {
            try
            {
                model.Item.Brand = model.Item.Brand.Trim();
                string uploadFolder = await UploadImages(model);
                string dir = "wwwroot\\" + uploadFolder;
                System.IO.Directory.CreateDirectory(dir);
                string fileName1 = "1.jpg";
                string fileName2 = "2.jpg";
                string fileName3 = "3.jpg";

                string file1 = System.IO.Path.Combine(dir, fileName1);
                string file2 = System.IO.Path.Combine(dir, fileName2);
                string file3 = System.IO.Path.Combine(dir, fileName3);

                using (Stream fileStream = new FileStream(file1, FileMode.Create))
                {
                    await model.File1.CopyToAsync(fileStream);
                }

                using (Stream fileStream = new FileStream(file2, FileMode.Create))
                {
                    await model.File2.CopyToAsync(fileStream);
                }

                using (Stream fileStream = new FileStream(file3, FileMode.Create))
                {
                    await model.File3.CopyToAsync(fileStream);
                }

                await _context.Item.AddAsync(model.Item);
                await _context.SaveChangesAsync();

                #region TwitterPost

                if (model.PublishItemFlag)
                {
                    PublishTweet(model.Item, uploadFolder);
                }

                #endregion TwitterPost
            }
            catch (Exception e)
            {
            }

            return RedirectToAction("ListItems", "Administration");
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            string[] files = Directory.GetFiles("wwwroot\\images\\items\\" + item.Title.Replace(" ", ""));

            IFormFile file1;
            IFormFile file2;
            IFormFile file3;

            using (var stream = System.IO.File.OpenRead(files[0]))
            {
                file1 = new FormFile(stream, 0, stream.Length, null, Path.GetFileName(stream.Name));
            }
            using (var stream = System.IO.File.OpenRead(files[1]))
            {
                file2 = new FormFile(stream, 0, stream.Length, null, Path.GetFileName(stream.Name));
            }
            using (var stream = System.IO.File.OpenRead(files[2]))
            {
                file3 = new FormFile(stream, 0, stream.Length, null, Path.GetFileName(stream.Name));
            }

            IQueryable<Item> allItems = _context.Item.Where(i => i.Active);

            List<Category> allCategories = await _context.Category.ToListAsync();

            var viewModel = new EditItemViewModel()
            {
                Item = item,
                LastItemName = item.Title,
                File1 = file1,
                File2 = file2,
                File3 = file3,

                categories = allCategories
            };

            //ViewData["CategoryId"] = new SelectList(_context.Set<Category>(), "Id", nameof(Category.Name), item.Category);
            return View(viewModel);
        }

        // POST: Items/Edit/5

src/GamingStore/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!doctype html>
<html  lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>GamingStore - Admin CP</title>
    <meta name="description" content="GamingStore - Admin Control Panel">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/css/administration/cs-skin-elastic.css">
    <link rel="stylesheet" href="~/css/administration/bar_chart_monthly_revenue.css">
    <link rel="stylesheet" href="~/css/administration/style.css">
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

</head>

<body>
    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="nav-link" asp-controller="Administration" asp-action="Index">
                            <i class="menu-icon fa fa-laptop"></i>Dashboard
                        </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-cogs"></i>User Settings</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li>
                                <i class="fa fa-puzzle-piece"></i> <a class="nav-link" asp-controller="Administration" asp-action="ListUsers">List Users</a>
                            </li>
                            <li>
                                <i class="fa fa-id-badge"></i> <a class="nav-link" asp-controller="Administration" asp-action="ListRoles">List Roles</a>
                            </li>
                        </ul>

                    <li>
                        <a class="nav-link" asp-controller="Administration" asp-action="ListOrders"><i class="menu-icon ti-receipt "></i>Orders</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-controller="Administration" asp-action="ListItems"><i class="menu-icon fa fa-barcode"></i>Items</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-controller="Administration" asp-action="ListCategories"><i class="menu-icon fa fa-list-alt"></i>Categories</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-controller="Administration" asp-action="ListStores"><i class="menu-icon fa fa-caret-square-o-up"></i>Stores</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="Logo">
                    </a>
                    <a class="navbar-brand hidden" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="Logo">
                    </a>
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">
                    <div class="header-left">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </header>
        <!-- /#header -->
        <!-- Content -->
        <main role="main">
            <div class="content">
                <div class="animated fadeIn">
                    @RenderBody()
                </div>
            </div>
        </main>
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
    </div>
    <!-- /#right-panel -->
    <!-- Scripts -->
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="/lib/notifyjs/notify.min.js"></script>
    <!-- D3 js-->
    <script src="https://d3js.org/d3.v6.min.js"></script>
    <script src="https://d3js.org/d3-format.v2.min.js"></script>
    <script src="https://d3js.org/d3-path.v2.min.js"></script>
    <script src="https://d3js.org/d3-shape.v2.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/GamingStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using GamingStore.Data
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject GamingStoreContext GamingStoreContext
<!DOCTYPE html>
<html lang="en" style="font-family: 'Rubik', sans-serif">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GamingStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <!---TopBar-->
        <nav style="background-color: #fff!important; margin-bottom: 0!important" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container d-flex flex-wrap">
                <ul class="nav me-auto">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-open" viewBox="0 0 16 16">
                        <path d="M8.47 1.318a1 1 0 0 0-.94 0l-6 3.2A1 1 0 0 0 1 5.4v.818l5.724 3.465L8 8.917l1.276.766L15 6.218V5.4a1 1 0 0 0-.53-.882l-6-3.2zM15 7.388l-4.754 2.877L15 13.117v-5.73zm-.035 6.874L8 10.083l-6.965 4.18A1 1 0 0 0 2 15h12a1 1 0 0 0 .965-.738zM1 13.117l4.754-2.852L1 7.387v5.73zM7.059.435a2 2 0 0 1 1.882 0l6 3.2A2 2 0 0 1 16 5.4V14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5.4a2 2 0 0 1 1.059-1.765l6-3.2z" />
                    </svg>
                    <a href="mailto:support@nyo.com" style="margin-left: 10px">nyo.gamings@gmail.com</a>
                </ul>
                @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin") ))
                {
                    <div class="top_bar_contact_item">
                        <a asp-controller="Administration" asp-action="Index">Admin CP</a>
                    </div>
                }
                <ul class="nav">
                    <div class="ml-auto">
                        <partial name="_LoginPartial" />

                    </div>
                </ul>
            </div>
        </nav>
        <!--MainBar-->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white  box-shadow mb-3" style="background-color: #edf1f4 !important; margin-bottom: 0 !important">
            <div class="container d-flex flex-wrap">
                <ul class="nav me-auto">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="card-img-top logo" src="~/images/logo.png" alt="Card image cap" style="width: 300px !important;">
                    </a>
                </ul>
            </div>

        </nav>
        <!--TabBar-->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-color: #edf1f4 !important;">
            <div class="container d-flex flex-wrap">
                <ul class="nav me-auto">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                        <ul class="col-lg-6 col-12 order-lg-2 order-3 text-lg-left text-right navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <strong>
                                    <a class="nav-link text-dark" style="margin-right: 100px" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </strong>
                            </li>
                            <li class="nav-item">
                                <strong><a class="nav-link text-dark" style="margin-right: 100px" asp-area="" asp-controller="Items" asp-action="Index">Items</a></strong>
                            </li>
                            <li class="nav-item">
                                <strong> <a class="nav-link text-dark" style="margin-right: 100px" asp-area="" asp-controller="Stores" asp-action="Index">Stores</a></strong>
                            </li>
                            <li class="nav-item">
                                <strong><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></strong>
                            </li>
                        </ul>
                    </div>
                </ul>
                <a asp-action="Index" asp-controller="Carts" class="nav-link link-dark px-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                    <span class="badge badge-light"
                    <div class="cart_count">
                                        <span id="cart_items_count">@Model?.ItemsInCart</span>
                                    </div>
                    </span>
                </a>
            </div>

        </nav>
    </header>


    <div class="container" style="margin-top: 1%">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--Footer-->
    <div style="background: #fafafa; width: 100%; padding-top: 60px; padding-bottom: 60px; box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);">
        <footer class="footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 footer_col">
                        <div class="footer_column footer_contact">
                            <div class="logo_container">
                                <div class="logo">
                                    <canvas id="FooterCanvas" width="300" height="100"></canvas>
                                </div>
                            </div>
                            <div class="footer_title">Got Question? Call Us 24/7</div>
                            <div class="footer_phone">+972 54 259 0925</div>
                            <div class="footer_contact_text">
                                <p>50 Dizengoff Street, Tel Aviv</p>
                                <p>Israel</p>
                            </div>
                            <div class="footer_social">
                                <ul>
                                    <li>
                                        <a href="https://twitter.com/NYO_GamingStore">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-2 offset-lg-1">
                        <div class="footer_column">
                            <div class="footer_title">Find it Fast</div>
                            <ul class="footer_list">
                                @{
                                    var categories = new List<Category>();
                                    categories.AddRange(GamingStoreContext.Category.Select(category => category));

                                    foreach (var category in categories)
                                    {
                                        <li>
                                            <a href="/Items/CategoryItems/@category.Id">@Html.DisplayFor(e => category.Name)</a>
                                        </li>

                                    }
                                }
                            </ul>
                        </div>
                    </div>

                    <div class=" col-lg-0 offset-lg-1">
                        <div class="footer_column">
                            <div class="footer_title"> Navigation</div>
                            <ul class="footer_list">
                                <li>
                                    <a href="/Stores">Stores</a>
                                </li>
                                <li>
                                    <a href="/Items">Items</a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class=" col-lg-2 offset-lg-1">
                        <div class="footer_column">
                            <div class="footer_title">Customer Care</div>
                            <ul class="footer_list">
                                <li>
                                    <a href="/Identity/Account/Manage">My Account</a>
                                </li>
                                <li>
                                    <a href="/Identity/Account/Manage/MyOrders">Order Tracking</a>
                                </li>
                                <li>
                                    <a href="/Home/Contact">Customer Services</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        @*<footer class="border-top footer text-muted" style="background-color: #edf1f4 !important;">
                <div class="container">
                    &copy; 2021 - GamingStore - Nitzan Miranda, Ori Bachar and Yuval Amir.
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-linkedin"></a>
                    <a href="#" class="fa fa-instagram"></a>
                </div>
            </footer>*@


    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/notifyjs/notify.min.js"></script>
    <script type="text/javascript" src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)

</body>
<script>
    var canvas = document.getElementById("FooterCanvas");
    var ctx = canvas.getContext("2d");
    ctx.font = "35px Arial";
    ctx.fillText("Gaming Store", 0, 40);
</script>

</html>