src/GamingStore/Models/Store.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Policy;
using System.Threading;
using GamingStore.Contracts;
using GamingStore.Models.Relationships;

namespace GamingStore.Models
{
    public class Store
    {
        public static int StoreCounter;

        public Store()
        {
            Orders = new List<Order>();
            StoreItems = new List<StoreItem>();
            Id = StoreCounter;
            Interlocked.Increment(ref StoreCounter);
        }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }

        [Required, DataType(DataType.Text), StringLength(50)]
        public string Name { get; set; }

        [Required]
        public Address Address { get; set; }

        [DisplayName("Phone")]
        [Required]
        [RegularExpression("^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-/0-9]*$", ErrorMessage = "Please enter a valid phone number.")]
        public string PhoneNumber { get; set; }

        [Required]
        //[DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Please enter a valid email address.")]
        public string Email { get; set; }

        [DisplayName("Opening Hours")]
        public List<OpeningHours> OpeningHours { get; set; } = new List<OpeningHours>(7);

        //public Dictionary<Item,uint> Stock { get; set; } // determines how many items there are in the store. example: {{fridge, 5},{mouse,6}}
        public ICollection<Order> Orders { get; set; }

        public ICollection<StoreItem> StoreItems { get; set; } // many to many relationship
        public bool Active { get; set; } = true;

        public bool IsOpen()
        {
            var currentDateTime = DateTime.Now;
            var dayOfWeek = (int)currentDateTime.DayOfWeek;
            var curTime = currentDateTime.TimeOfDay;

            //return true;
            return TimeSpan.Parse(OpeningHours[dayOfWeek].OpeningTime) <= curTime && curTime <= TimeSpan.Parse(OpeningHours[dayOfWeek].ClosingTime);
        }
    }
}

src/GamingStore/ViewModels/Stores/CreateStoreViewModel.cs
using GamingStore.Models;

namespace GamingStore.ViewModels.Stores
{
    public class CreateStoreViewModel : ViewModelBase
    {
        public Store Store { get; set; }
    }
}

src/GamingStore/ViewModels/Stores/StoreDetailsViewModel.cs
using GamingStore.Models;

namespace GamingStore.ViewModels.Stores
{
    public class StoreDetailsViewModel : ViewModelBase
    {
        public Store Store { get; set; }
    }
}

src/GamingStore/ViewModels/Stores/StoresCitiesViewModel.cs
using System.Collections.Generic;
using GamingStore.Models;

namespace GamingStore.ViewModels.Stores
{
    public class StoresCitiesViewModel : ViewModelBase
    {
        public IEnumerable<Store> Stores { get; set; }

        public string[] CitiesWithStores { get; set; }
        public IEnumerable<Store> OpenStores{ get; set; }

        public Dictionary<string,double> CurrentWeather { get; set; } 
        public string Name { get; set; }
        public string City { get; set; }
        public bool IsOpen { get; set; } 
    }
}

src/GamingStore/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Accuweather;
using GamingStore.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GamingStore.Data;
using GamingStore.Models;
using GamingStore.Models.Relationships;
using GamingStore.ViewModels;
using GamingStore.ViewModels.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using RestSharp;

namespace GamingStore.Controllers
{
    public class StoresController : BaseController
    {
        private static readonly IAccuweatherApi _accuweatherApi = new AccuweatherApi("I7i66pnCspYN80KAWUGeAbMoo0dkdsLc");

        public StoresController(UserManager<User> userManager, GamingStoreContext context, RoleManager<IdentityRole> roleManager, SignInManager<User> signInManager)
            : base(userManager, context, roleManager, signInManager)
        {
        }

        // GET: Stores
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Store> stores = await Context.Store.ToListAsync();
            HashSet<string> uniqueCities = GetUniqueCities(stores);
            List<Store> openStores = GetOpenStores(stores);
            Dictionary<string, double> weather = GetCurrentWeather(uniqueCities);
            var viewModel = new StoresCitiesViewModel
            {
                Stores = stores,
                CitiesWithStores = uniqueCities.ToArray(),
                OpenStores = openStores,
                CurrentWeather = weather,
                ItemsInCart = await CountItemsInCart()
            };

            return View(viewModel);
        }

        private static List<Store> GetOpenStores(List<Store> stores)
        {
            List<Store> openStores = stores.Where(store => store.IsOpen()).ToList(); // get open stores

            return openStores;
        }

        // Post: Stores //the search function
        [HttpPost]
        public async Task<IActionResult> Index(StoresCitiesViewModel received)
        {
            List<Store> stores = await Context.Store.ToListAsync();
            HashSet<string> uniqueCities = GetUniqueCities(stores);

            // get open stores
            List<Store> openStores = stores.Where(store => store.IsOpen()).ToList();

            if (!string.IsNullOrEmpty(received.Name))
            {
                stores = stores.Where(store => store.Name.ToLower().Contains(received.Name.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(received.City))
            {
                stores = stores.Where(store => store.Address.City == received.City).ToList();
            }

            if (received.IsOpen)
            {
                stores = stores.Where(store => store.IsOpen()).ToList();
            }
            Dictionary<string, double> weather = GetCurrentWeather(uniqueCities);
            var viewModel = new StoresCitiesViewModel
            {
                Stores = stores,
                CitiesWithStores = uniqueCities.ToArray(),
                OpenStores = openStores,
                Name = received.Name,
                City = received.City,
                CurrentWeather = weather,
                IsOpen = received.IsOpen,
                ItemsInCart = await CountItemsInCart()
            };

            return View(viewModel);
        }


        private static HashSet<string> GetUniqueCities(List<Store> stores)
        {
            // get stores with cities uniquely 
            var uniqueCities = new HashSet<string>();

            foreach (Store element in stores)
            {
                if (!string.IsNullOrWhiteSpace(element.Address.City))
                {
                    uniqueCities.Add(element.Address.City);
                }
            }

            return uniqueCities;
        }

        private static Dictionary<string, double> GetCurrentWeather(HashSet<string> stores)
        {
            var weather = new Dictionary<string, double>();

            foreach (var store in stores)
            {
                try
                {
                    if(store == String.Empty)
                        continue;
                    var client = new RestClient("http://api.weatherapi.com/v1/");
                    var request = new RestRequest("current.json", Method.GET);
                    request.AddParameter("key", "df7bc763685d44b68aa114413211906");
                    request.AddParameter("q", store);
                    var response = client.Execute(request);
                    var weatherByCity = JsonConvert.DeserializeObject<Root>(response.Content);
                    weather.Add(store, weatherByCity.current.temp_c);
                }
                catch (Exception e)
                {
                    continue;
                }
            }

            return weather;
        }

        // GET: Stores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Store store = await Context.Store.FirstOrDefaultAsync(m => m.Id == id);
            if (store == null)
            {
                return NotFound();
            }

            var viewModel = new StoreDetailsViewModel()
            {
                Store = store,
                ItemsInCart = await CountItemsInCart()
            };

            return View(viewModel);
        }

        // GET: Stores/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var viewModel = new CreateStoreViewModel()
            {
                Store = new Store()
                {
                    Active = true,
                    OpeningHours = new List<OpeningHours>(7)
                    {
                        new OpeningHours() { OpeningTime = "00:00", ClosingTime = "00:00", DayOfWeek = DayOfWeek.Sunday },
                        new OpeningHours() { OpeningTime = "00:00", ClosingTime = "00:00", DayOfWeek = DayOfWeek.Monday },
                        new OpeningHours() { OpeningTime = "00:00", ClosingTime ="00:00", DayOfWeek = DayOfWeek.Tuesday },
                        new OpeningHours() { OpeningTime = "00:00", ClosingTime = "00:00", DayOfWeek = DayOfWeek.Wednesday },
                        new OpeningHours() { OpeningTime = "00:00", ClosingTime = "00:00", DayOfWeek = DayOfWeek.Thursday },
                        new OpeningHours() { OpeningTime = "00:00", ClosingTime = "00:00", DayOfWeek = DayOfWeek.Friday },
                        new OpeningHours() { OpeningTime = "00:00", ClosingTime = "00:00", DayOfWeek = DayOfWeek.Saturday }
                    },
                    Address = new Address()
                    {
                        Country = "Israel"
                    }
                },
                ItemsInCart = await CountItemsInCart()
            };

            return View(viewModel);
        }

        // POST: Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,PhoneNumber,Email,OpeningHours")] Store store, string street, int number, string city, string Open0, string Open1, string Open2, string Open3, string Open4, string Open5, string Open6, string Close0, string Close1, string Close2, string Close3, string Close4, string Close5, string Close6)
        {
            var viewModel = new CreateStoreViewModel()
            {
                Store = store,
                ItemsInCart = await CountItemsInCart()
            };

            store.OpeningHours = new List<OpeningHours>();
            List<string> days = new List<string>();
            days.Add(Open0);
            days.Add(Open1);
            days.Add(Open2);
            days.Add(Open3);
            days.Add(Open4);
            days.Add(Open5);
            days.Add(Open6);
            days.Add(Close0);
            days.Add(Close1);
            days.Add(Close2);
            days.Add(Close3);
            days.Add(Close4);
            days.Add(Close5);
            days.Add(Close6);
            for (var i = 0; i < 7; i++)
            {
                DayOfWeek day = (DayOfWeek) i;
                OpeningHours temp = new OpeningHours();
                temp.DayOfWeek = day;
                temp.OpeningTime = days[i];
                temp.ClosingTime = days[i + 7];

                store.OpeningHours.Add(temp);
            }


             
            if (store.OpeningHours.Any(openingHour => TimeSpan.Parse(openingHour.ClosingTime) <=  TimeSpan.Parse(openingHour.OpeningTime)))
            {
                ModelState.AddModelError("", "Opening hours needs to be earlier than closing hours.");
                return View(viewModel);
            }
            
            
            /*
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            */
            Context.Add(store);
            await Context.SaveChangesAsync();

            return RedirectToAction("ListStores", "Administration");
        }

        // GET: Stores/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!StoreExists(id.Value))
            {
                return RedirectToAction("ListStores", "Administration");
            }

            Store store = await Context.Store.FindAsync(id);
            var viewModel = new StoreDetailsViewModel()
            {
                Store = store,
                ItemsInCart = await CountItemsInCart()
            };

src/GamingStore/Views/Stores/Create.cshtml
@model GamingStore.ViewModels.Stores.CreateStoreViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Create a new Store</strong>
            </div>
            <div class="card-body card-block">
                <div class="column">
                    <form asp-action="Create">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="@Model.Store.Name" class="control-label"></label>
                            <input asp-for="@Model.Store.Name" class="form-control" />
                            <span asp-validation-for="@Model.Store.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Store.Address" class="control-label"></label>
                            <input asp-for="@Model.Store.Address.Street" class="form-control" placeholder="Street" />
                            <span asp-validation-for="@Model.Store.Address.Street" class="text-danger"></span>
                            <input type="text" asp-for="@Model.Store.Address.Number" class="form-control" placeholder="Number" />
                            <span asp-validation-for="@Model.Store.Address.Number" class="text-danger"></span>
                            <input asp-for="@Model.Store.Address.City" class="form-control" placeholder="City" />
                            <span asp-validation-for="@Model.Store.Address.City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Store.PhoneNumber" class="control-label"></label>
                            <input asp-for="@Model.Store.PhoneNumber" class="form-control" />
                            <span asp-validation-for="@Model.Store.PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Store.Email" class="control-label"></label>
                            <input asp-for="@Model.Store.Email" class="form-control" />
                            <span asp-validation-for="@Model.Store.Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Store.OpeningHours" class="control-label"></label>
                            <table class="opening_hours">
                                <tr>
                                    @{
                                        foreach (var day in Model.Store.OpeningHours)
                                        {
                                            <th> @day.DayOfWeek.ToString().Substring(0, 3)</th>
                                        }
                                    }
                                </tr>
                                <tr>
                                    @{
                                        for (var i = 0; i < 7; i++)
                                        {
                                            var open = "Open" + @i;
                                            var close = "Close" + @i;
                                            <td>
                                                <span>
                                                    <input type="time" name="@open" class="form-control" asp-for="@Model.Store.OpeningHours[i].OpeningTime" required />
                                                </span>
                                                <span>
                                                    <input type="time" name="@close" class="form-control" asp-for="@Model.Store.OpeningHours[i].ClosingTime" required />
                                                </span>
                                            </td>
                                        }
                                    }
                                </tr>
                            </table>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@Model.Store.Active" /> @Html.DisplayNameFor(model => model.Store.Active)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

src/GamingStore/Views/Stores/Delete.cshtml
@model GamingStore.ViewModels.Stores.StoreDetailsViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-header">
                <strong>Are you sure you want to delete this store?</strong>
            </div>
            <div class="card-body card-block">
                <div class="column">
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Store.Name)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Store.Name)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Store.Address)
                            </dt>
                            <dd class="col-sm-10">
                                <lable>@Model.Store.Address.ToString()</lable>
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Store.PhoneNumber)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Store.PhoneNumber)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Store.Email)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Store.Email)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Store.OpeningHours)
                            </dt>
                            <dd class="col-sm-10">
                                <table class="opening_hours">
                                    <tr>
                                        @{
                                            foreach (var day in Model.Store.OpeningHours)
                                            {
                                                <th> @day.DayOfWeek.ToString().Substring(0, 3)</th>
                                            }
                                        }
                                    </tr>
                                    <tr>
                                        @{
                                            for (var i = 0; i < 7; i++)
                                            {
                                                var open = "Open" + @i;
                                                var close = "Close" + @i;
                                                <td>
                                                    <div>
                                                        <lable>@Model.Store.OpeningHours[i].OpeningTime</lable>
                                                    </div>

                                                    <div>
                                                        <lable>@Model.Store.OpeningHours[i].ClosingTime</lable>
                                                    </div>
                                                </td>
                                            }
                                        }
                                    </tr>
                                </table>
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Store.Active)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Store.Active)
                            </dd>
                        </dl>

                        <form asp-action="DeleteConfirmed">
                            <input type="hidden" name="id" value="@Model.Store.Id" />
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

src/GamingStore/Views/Stores/Details.cshtml
@model GamingStore.ViewModels.Stores.StoreDetailsViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Store</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store.Address)
        </dt>
        <dd class="col-sm-10">
            <lable>@Model.Store.Address.ToString()</lable>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store.OpeningHours)
        </dt>
        <dd class="col-sm-10">
            <table class="opening_hours">
                <tr>
                    @{
                        foreach (var day in Model.Store.OpeningHours)
                        {
                            <th> @day.DayOfWeek.ToString().Substring(0, 3)</th>
                        }
                    }
                </tr>
                <tr>
                    @{
                        for (var i = 0; i < 7; i++)
                        {
                            var open = "Open" + @i;
                            var close = "Close" + @i;
                            <td>
                                <div>
                                    <lable>@Model.Store.OpeningHours[i].OpeningTime</lable>
                                </div>

                                <div>
                                    <lable>@Model.Store.OpeningHours[i].ClosingTime</lable>
                                </div>
                            </td>
                        }
                    }
                </tr>
            </table>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.Active)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Store.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/GamingStore/Views/Stores/Index.cshtml
@using GamingStore.Contracts
@using System.Text.RegularExpressions
@using Microsoft.EntityFrameworkCore.ChangeTracking.Internal
@using Accuweather
@model GamingStore.ViewModels.Stores.StoresCitiesViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@functions
{
    void OpeningHoursTemplate(Store store)
    {
        <div class="store_detail">
            Opening Hours:
            <table class="opening_hours">
                <tr>
                    @{
                        foreach (var day in store.OpeningHours)
                        {
                            <th> @day.DayOfWeek.ToString().Substring(0, 3)</th>
                        }
                    }
                </tr>
                <tr>
                    @{
                        foreach (var day in store.OpeningHours)
                        {
                            <td>
                                <span>
                                    @day.OpeningTime
                                </span>
                                <span>
                                    @day.ClosingTime
                                </span>
                            </td>
                        }
                    }
                </tr>
            </table>
        </div>
    }

    void StoreTemplate(Store store)
    {
        <li class="list-group-item list-group-item-action" id="store_@store.Id" data-toggle="list" role="tab" aria-controls="store_@store.Id">
            @{ var isWebsite = store.Name == "Website" ? true : false; }
            <div class="store_title">
                <h4>
                    @{
                        var storeName = store.Name.Replace("Store", "");
                    }
                    @Html.DisplayFor(modelItem => storeName)
                </h4>
            </div>
            <div class="store_detail store_address">
                @{
                    var address = store.Address.ToString();
                    <script>
            storesObject.push(["@address", "@storeName", "@isWebsite".toLowerCase()]);
                    </script>
                }
                @Html.DisplayFor(modelItem => address)
            </div>
            <div class="store_detail store_phonenumber">
                Phone:
                <a href="tel:@store.PhoneNumber">@Regex.Replace(store.PhoneNumber, @"(\d{3})(\d{3})(\d{4})", "+$1-$2-$3")</a>
            </div>
            <div class="store_detail store_email">
                Email:
                <a href="mailto:@store.Email">@store.Email </a>
            </div>
            <div class="store_detail store_email">

                @{
                    if (store.Address.City == "")
                    {
                        <div>Weather: No weather in the big world wide web. &#127760;</div>
                    }
                    else
                    {
                        var temp = Model.CurrentWeather.GetValueOrDefault(store.Address.City);
                        <div>

                            @{
                                if (temp > 16)
                                {
                                    <div>Weather: @temp Celsius &#127774;</div>
                                }
                                if (temp < 16 && temp > 10)
                                {
                                    <div>Weather: @temp Celsius &#9925;</div>
                                }

                                if (temp < 10)
                                {
                                    <div>Weather: @temp Celsius &#9924;</div>
                                }
                            }
                        </div>
                    }
                }

            </div>

            @{ OpeningHoursTemplate(store); }
        </li>
    }
}

<head>
    <link rel="stylesheet" type="text/css" href="~/css/store_style.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap" rel="stylesheet">
    <script>
        var storesObject = [];
    </script>
</head>

<div class="store_container">
    <div class="container">
        <h3>Which Store are you looking for?</h3>
        @using (Html.BeginForm("Index", "Stores", FormMethod.Post, new { @class = "search_form" }))
        {
            <div class="input-group mb-3">
                <div class="input-group-prepend  search_bar">
                    @Html.TextBoxFor(sc => sc.Name, new { @class = "form-control", @id = "searchStoreString", @placeholder = "Search Store" })
                </div>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    @Html.Label("cityInputGroup", "City", new { @class = "input-group-text" })
                </div>
                @Html.DropDownListFor(sc => sc.City, new SelectList(Model.CitiesWithStores), "Select City", new { @class = "custom-select", @id = "cityInputGroup" })
            </div>
            <div class="form-group form-check">
                @Html.CheckBoxFor(m => m.IsOpen, new { @class = "form-check-input", @id = "isOpen" })
                @Html.Label("isOpen", "Search only open stores")
            </div>
            <button asp-action="Index" asp-controller="Stores" type="submit" class="btn btn-primary" id="searchSubmit">Search</button>
        }
        <div class="row">
            <div class="col-lg-5">
                <ul class="list-group store_list" id="storesList" role="tablist">
                    @foreach (var store in Model.Stores)
                    {
                        StoreTemplate(store);
                    }
                </ul>

            </div>
            <div class="col-lg-7">
                <div class="store_map" id="map"></div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @*loads after all scripts are rendered like jQuery and scripts from _NewLayout https://stackoverflow.com/questions/37923853/how-to-use-jquery-in-asp-net-core/37923947*@
    <script type="text/javascript" src="/js/stores.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD796WpAS05Nrt9Ojss_POoKnHHD5vvrLk&callback=initMap" type="text/javascript"></script>
}